### PR TITLE
Fix bug in AsyncTimedRotatingFileHandler

### PR DESCRIPTION
**Pull request by bokailya**
Fixed bug with removing latest log files instead of oldest

## Todo
- [ ] Add a new test case that confirms the new desired behavior;

### CODE REVIEW

**Comment by daltonmatos** [comment]
Hello @bokailya,

Could you elaborate more on the issue you were facing that this PR fixes, please?

This line was changes a while ago in this commit (bc7def2c0400969d2156fa028679996f21941609) and I'm afraid that this PR could bring back the bug that was fixed in the past.

**Comment by bokailya** [comment]
Hello @daltonmatos , thank you for your response.

I could give you minimal reproducible example:

```from asyncio import run
from asyncio import sleep

from aiologger import Logger
from aiologger.handlers.files import AsyncTimedRotatingFileHandler
from aiologger.handlers.files import RolloverInterval


async def main() -> None:
    logger = Logger(name='test_logger')
    logger.add_handler(
        AsyncTimedRotatingFileHandler(
            filename='test_log.txt',
            backup_count=1,
            interval=1,
            when=RolloverInterval.SECONDS,
        ),
    )

    await logger.info('1')
    await sleep(1)
    await logger.info('2')
    await sleep(1)
    await logger.info('3')

if __name__ == '__main__':
    run(main())
```

It leaves me two log files:

```
$ cat test_log.txt
3
$ cat test_log.txt.2020-10-03_19-35-53 
1
```
I got backup of the first written log file, but i would prefer to get latest log data in the backup as done by synchronous TimedRotatingFileHandler from Python standard library (You can find implementation here https://github.com/python/cpython/blob/3.8/Lib/logging/handlers.py#L360).

**Comment by daltonmatos** [comment]
Hello @bokailya, I was planning to take a closer loop at this today but didn't have time.

Could you add a testcase for this fix before we can merge this PR?

Thanks,

**Review by daltonmatos — CHANGES_REQUESTED** [review]
I think a new test case should be added that confirms the behavior we want.

**Comment by dvenum** [comment]
This bug is here:
https://github.com/b2wdigital/aiologger/blob/master/aiologger/handlers/files.py#L407

You sort it reverse and delete first files, but this is new files:
`
0:'/logs/test.log.2021-01-13_14-39-44'
1:'/logs/test.log.2021-01-13_14-22-43'
2:'/logs/test.log.2021-01-13_14-22-42'
3:'/logs/test.log.2021-01-13_14-22-41'
`

**Pull request closed without merging**
